name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' 

      - name: Install dependencies
        run: npm ci
        
      - name: Run TypeScript type check
        run: npm run type-check

      - name: Build the project
        run: npm run build

      - name: Run unit tests with Vitest
        run: npm run test:unit

      - name: Run Cypress E2E tests
        run: npm run test:e2e
        env:
          CYPRESS_baseUrl: http://localhost:4173
